spring.application.name=wmat

# Database Configuration - Use separate environment variables
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# PostgreSQL Dialect for Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Secret Key
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Disable DataSeeder in production
app.seeder.enabled=false
